import { createClient } from './supabase/client';

/**
 * Increments the download count for an exam and triggers the download
 * @param {string} examId 
 * @param {string} examTitle 
 */
export async function downloadExamPaper(examId, examTitle) {
  const supabase = createClient();

  try {
    // 1. Increment download count (optimistic update if we had a state, but here we just hit DB)
    // We use RPC for atomic increment if available, or just a regular update
    const { error: incError } = await supabase.rpc('increment_exam_downloads', { exam_id: examId });
    
    if (incError) {
      // Fallback if RPC isn't set up yet
      const { data: currentData } = await supabase
        .from('exams')
        .select('downloads')
        .eq('id', examId)
        .single();
      
      await supabase
        .from('exams')
        .update({ downloads: (currentData?.downloads || 0) + 1 })
        .eq('id', examId);
    }

    // 2. Fetch full exam data
    const { data: sections, error: secError } = await supabase
      .from('sections')
      .select('*')
      .eq('exam_id', examId)
      .order('sort_order', { ascending: true });

    if (secError) throw secError;

    const { data: questions, error: qError } = await supabase
      .from('questions')
      .select('*')
      .eq('exam_id', examId)
      .order('question_number', { ascending: true });

    if (qError) throw qError;

    // 3. Format as a readable text document
    let content = `====================================================\n`;
    content += `         SOMALI NATIONAL EXAM REPOSITORY\n`;
    content += `====================================================\n\n`;
    content += `EXAM: ${examTitle.toUpperCase()}\n`;
    content += `DATE DOWNLOADED: ${new Date().toLocaleDateString()}\n`;
    content += `----------------------------------------------------\n\n`;

    sections.forEach(section => {
      content += `\n[ ${(section.section_name || 'SECTION').toUpperCase()} ]\n`;
      content += `----------------------------------------------------\n`;
      
      const sectionQuestions = questions.filter(q => q.section_id === section.id);
      
      sectionQuestions.forEach((q, idx) => {
        content += `\n${q.question_number || (idx + 1)}. ${q.question_text}\n`;
        
        if (q.option_a && q.option_b) {
          if (q.option_a) content += `   A) ${q.option_a}\n`;
          if (q.option_b) content += `   B) ${q.option_b}\n`;
          if (q.option_c) content += `   C) ${q.option_c}\n`;
          if (q.option_d) content += `   D) ${q.option_d}\n`;
          content += `\n   Correct Answer: ${q.correct_answer}\n`;
        } else {
          content += `\n   Answer/Explanation: ${q.explanation || q.correct_answer || 'N/A'}\n`;
        }
        content += `\n`;
      });
    });

    const orphanedQuestions = questions.filter(q => !q.section_id);
    if (orphanedQuestions.length > 0) {
      content += `\n[ GENERAL QUESTIONS ]\n`;
      content += `----------------------------------------------------\n`;
      orphanedQuestions.forEach((q, idx) => {
        content += `\n${q.question_number || (idx + 1)}. ${q.question_text}\n`;
        
        if (q.option_a && q.option_b) {
          if (q.option_a) content += `   A) ${q.option_a}\n`;
          if (q.option_b) content += `   B) ${q.option_b}\n`;
          if (q.option_c) content += `   C) ${q.option_c}\n`;
          if (q.option_d) content += `   D) ${q.option_d}\n`;
          content += `\n   Correct Answer: ${q.correct_answer}\n`;
        } else {
          content += `\n   Answer/Explanation: ${q.explanation || q.correct_answer || 'N/A'}\n`;
        }
        content += `\n`;
      });
    }

    content += `\n\n====================================================\n`;
    content += `Generated by Zeweno Platform - zeweno.com\n`;
    content += `====================================================\n`;

    // 4. Trigger download
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${examTitle.replace(/\s+/g, '_')}_Paper_With_Answers.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    return true;
  } catch (err) {
    console.error('Download failed:', err);
    return false;
  }
}
